api_key: APIMGpn7kZ7YUgU
api_secret: NUReZAOWK47i7tt26G8yKl8it8GcmyId8psiN7hhTXP
ws_url: ws://localhost:7880
redis:
  address: localhost:6379
sip_port: 5060
rtp_port: 10000-20000
use_external_ip: true
logging:
  level: debug