version: "3.8"

services:
  # LiveKit server
  livekit:
    image: livekit/livekit-server:latest
    command: --config /etc/livekit.yaml
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./livekit.yaml:/etc/livekit.yaml

  # SIP service
  sip:
    image: livekit/sip
    command: --config /etc/config.yaml
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./config.yaml:/etc/config.yaml

  # Redis
  redis:
    image: redis:7-alpine
    command: redis-server /etc/redis.conf
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./redis.conf:/etc/redis.conf



  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: >
      sh -c "
        if [ ! -f /etc/letsencrypt/live/livekitsecrets.gleeze.com/fullchain.pem ]; then
          echo '>>> First run: issuing new cert...';
          certbot certonly --webroot --webroot-path=/var/www/certbot \
            --email mahmoudmuhammed255@gmail.com \
            --agree-tos --no-eff-email \
            -d livekitsecrets.gleeze.com;
        fi;
        echo '>>> Starting renew loop...';
        trap exit TERM;
        while :; do
          certbot renew --webroot --webroot-path=/var/www/certbot --quiet;
          sleep 12h & wait $${!};
        done
      "


  # Egress
  egress:
    image: livekit/egress:latest
    restart: unless-stopped
    network_mode: "host"
    environment:
      - EGRESS_CONFIG_FILE=/etc/egress.yaml
    volumes:
      - ./egress.yaml:/etc/egress.yaml
    cap_add:
      - CAP_SYS_ADMIN

  # Ingress
  ingress:
    image: livekit/ingress:latest
    restart: unless-stopped
    network_mode: "host"
    environment:
      - INGRESS_CONFIG_FILE=/etc/ingress.yaml
    volumes:
      - ./ingress.yaml:/etc/ingress.yaml