# This docker-compose requires host networking, which is only available on Linux
# This compose will not function correctly on Mac or Windows
services:
  livekit:
    image: livekit/livekit-server:latest
    command: --config /etc/livekit.yaml
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./livekit.yaml:/etc/livekit.yaml
  sip:
    image: livekit/sip
    network_mode: "host"
    command: --config /etc/config.yaml
    volumes:
      - ./config.yaml:/etc/config.yaml
      - ./certbot/conf:/etc/letsencrypt
  redis:
    image: redis:7-alpine
    command: redis-server /etc/redis.conf
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./redis.conf:/etc/redis.conf
  certbot:
    image: certbot/certbot
    container_name: certbot
    network_mode: "host"
    volumes: 
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: [
      "certonly",
      "--webroot",
      "-w", "/var/www/certbot",
      "--staging",
      "--non-interactive",
      "--force-renewal",
      "--email", "mahmoudmuhammed255@gmail.com",
      "-d", "livekitsecrets.gleeze.com",
      "--agree-tos"
    ]
  nginx:
        container_name: nginx
        restart: unless-stopped
        image: nginx
        network_mode: "host"
        ports:
            - 80:80
            - 443:443
        volumes:
          - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
          - ./certbot/www:/var/www/certbot   # certbot challenge dir
          - ./certbot/conf:/etc/letsencrypt  # certs storage

  egress:
    image: livekit/egress:latest
    restart: unless-stopped
    environment:
      - EGRESS_CONFIG_FILE=/etc/egress.yaml
    network_mode: "host"
    volumes:
      - ./egress.yaml:/etc/egress.yaml
    cap_add:
      - CAP_SYS_ADMIN
  ingress:
    image: livekit/ingress:latest
    restart: unless-stopped
    environment:
      - INGRESS_CONFIG_FILE=/etc/ingress.yaml
    network_mode: "host"
    volumes:
      - ./ingress.yaml:/etc/ingress.yaml